### ISSUE TITLE
Bug: Fail to validate artifacts

### ISSUE THREAD

**Issue by hangleang** [graphprotocol/graph-client#399] opened 2023-03-09 04:15 UTC
Hi guys, I tried to include `graphclient validate` command to verify the build artifacts into my CI pipeline, but it seems not work for graphql sources, especially for `subgraph`, even though it work properly when serve the service. below is the output of the command:
```
$ graphclient validate
💡 GraphClient Reading the configuration
💡 GraphClient Generating the unified schema
🐛 GraphClient - GetMesh Getting subschemas from source handlers
🐛 GraphClient - NFTs Generating the schema
💥 GraphClient - NFTs Failed to generate the schema Error: Failed to fetch introspection from https://api.thegraph.com/subgraphs/name/hangleang/nft-goerli: ValidationError: Validation failed for "introspectionSchema" under ".graphclient/sources/NFTs": 
    at doValidation (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/store/cjs/index.js:159:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.set (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/store/cjs/index.js:186:21)
    at async Object.getWithSet (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/store/cjs/index.js:172:25)
    at async Promise.allSettled (index 0)
    at async GraphQLHandler.getMeshSource (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/graphql/cjs/index.js:331:52)
    at async /home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:133:28
    at async Promise.allSettled (index 0)
    at async getMesh (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:128:5)
    at async Object.handler (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/cli/cjs/index.js:234:26)
    at GraphQLHandler.getMeshSource (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/graphql/cjs/index.js:336:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:133:28
    at async Promise.allSettled (index 0)
    at async getMesh (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:128:5)
    at async Object.handler (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/cli/cjs/index.js:234:26)
💥 GraphClient Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh.
    at getMesh (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:167:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/home/hangleang/Documents/projects/graphql/nft-marketplaces-gateway/node_modules/@graphql-mesh/cli/cjs/index.js:234:26)
```

**Comment by dotansimha** [comment] 2023-03-11 10:27
@ardatan can you please take a look?

**Comment by ardatan** [comment] 2023-05-29 11:41
Can you share a reproduction on CodeSandbox? Thanks!

**Comment by ardatan** [comment] 2023-08-01 12:53
Closing the issue due to the lack of a reproduction. Feel free to create a new one if you still have it.

**Closed by ardatan** 2023-08-01 12:53 UTC
