### ISSUE TITLE
Cross chain extension example suddenly failing with Type `Query` has no field `crossRebases`'

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#167] opened 2022-07-26 06:08 UTC
https://github.com/graphprotocol/graph-client/tree/main/examples/cross-chain-extension

Previously worked, I had 3 apps based on this but suddenly they all recieve "Type `Query` has no field `crossRebases`'" like error. I confirmed against your own minimal example here and same behavior.

**Comment by matthewlilley** [comment] 2022-07-26 06:14
It seems that an underlying library which wasn't pinned has been updated and is what is causing the error...

**Comment by matthewlilley** [comment] 2022-07-26 06:49
Tested each version from 1.0.1 to 2.0.2 and the issue persists, so expect this is related to an underlying library change which is not obvious.

**Comment by ardatan** [comment] 2022-07-26 16:03
We are currently working on the fix. You can add `merger: stitching` on top until we release a patch.

**Comment by matthewlilley** [comment] 2022-07-26 16:13
> We are currently working on the fix. You can add `merger: stitching` on top until we release a patch.

Thanks. I tried so many things last night but not this one. Appriciate the heads up on that.

**Comment by ardatan** [comment] 2022-07-26 17:37
Could you try with `@graphprotocol/client-cli@2.1.1`? Thanks!

**Comment by matthewlilley** [comment] 2022-07-26 17:58
@ardatan I just tested 2.1.1 but the same behavior it seems🤔

**Comment by matthewlilley** [comment] 2022-07-26 17:58
I will test your minimal example to be sure

**Comment by ardatan** [comment] 2022-07-26 18:00
@matthewlilley Make sure you run `graphclient build` again after updating dependencies because the generated code was broken.

**Comment by matthewlilley** [comment] 2022-07-26 18:04
@ardatan Minimal example seems to work, must be a caching issue on my end. Will try agian.

**Comment by ardatan** [comment] 2022-07-26 18:18
I also tested here;
https://codesandbox.io/s/musing-benz-od46cq?file=/src/index.ts

**Comment by matthewlilley** [comment] 2022-07-26 18:18
@ardatan Strange, I'm struggling with the latest version still...

Error: {"locations":[{"column":3,"line":2}],"message":"Type `Query` has no field `crossChainPairs`"}

**Comment by matthewlilley** [comment] 2022-07-26 18:20
Doubled checked my pnpm lock & node modules, all are on the latest version. Three apps are still failing with the same error.

**Comment by matthewlilley** [comment] 2022-07-26 18:21
In pnpm I have auto install peer deps as true, maybe something weird is happening with peer dependecies?

**Comment by matthewlilley** [comment] 2022-07-26 18:21
I will test

**Comment by matthewlilley** [comment] 2022-07-26 18:31
No difference.... Can you tell me what was the bad dependency so I can try and find it in the monorepo?

**Comment by matthewlilley** [comment] 2022-07-26 18:35
I'll try to add reproduction because I can't get this to work, it's producing exactly the same error on all 3 apps which previously worked.

**Comment by matthewlilley** [comment] 2022-07-26 18:43
@ardatan I'm not familiar with codesandbox. I seem to be unable to force it to build-client, but I made a reproduction here.

https://codesandbox.io/s/wizardly-snowflake-rze2bd?file=/src/index.ts

**Comment by matthewlilley** [comment] 2022-07-26 18:47
when I try to build in terminal I see:

/.graphclient/sources/Exchange/introspectionSchema.ts is larger than maximum allowed file size (1171257 > 524288), not synchronizing

so I guess it will not generate graphclient on codesandbox

**Comment by ardatan** [comment] 2022-07-26 18:50
You can ignore that warning. The configuration in the sandbox is wrong;
```
additionalResolvers:
  - ./src/resolvers.ts # This path is wrong in your CodeSandbox
```
Sorry but I really need to reproduce it in order to help you. You can try StackBlitz or some other similar platform. Feel free to share when you clearly reproduce it.

**Comment by matthewlilley** [comment] 2022-07-26 18:54
Ah, you know what it was... In our blog app we use @graphmesh/cli

I wonder if there's a better way to ensure these kind of conflicts can be avoided. Blog should be able to use a different version without affecting other applications, it's quite strange. Anyway, updating dependency in the blog solved the issue for other apps.

**Comment by matthewlilley** [comment] 2022-07-26 18:56
4 apps:

blog: @graphql-mesh/cli@^0.74.1 & @graphql-mesh/graphql@^0.29.1

internal dashboard: @graphprotocol/graph-client@2.1.1
lending dashboard: @graphprotocol/graph-client@2.1.1
liquidity dashboard: @graphprotocol/graph-client@2.1.1

blog dependency caused other unrelated apps to fail...

**Comment by ardatan** [comment] 2022-07-27 11:54
I think we can close this.
> I wonder if there's a better way to ensure these kind of conflicts can be avoided. Blog should be able to use a different version without affecting other applications, it's quite strange. Anyway, updating dependency in the blog solved the issue for other apps.

It happens to all of us actually. We prefer using `resolutions` for those cases or `npx yarn-deduplicate`

**Closed by ardatan** 2022-07-27 11:54 UTC
