### ISSUE TITLE
Scalars types are outside of the context scope

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#248] opened 2022-09-15 09:10 UTC
In the latest version, Scalars type is within the BentoBoxTypes namespace, however, the BentoBoxContext is outside of this scope but is still referencing the Scalar types.

![Screenshot_811](https://user-images.githubusercontent.com/6063350/190363879-60805307-b883-47a9-8b5b-30c5c0788f85.png)

![Screenshot_812](https://user-images.githubusercontent.com/6063350/190363888-140b4383-3965-45e7-9402-ab03bd08e0bf.png)

Trying to build anything which is consuming the code generated SDK with TypeScript strict mode enabled will fail.

**Comment by saihaj** [comment] 2022-09-15 16:38
can you share a reproduction repo for this?

**Comment by ardatan** [comment] 2022-09-15 17:16
I believethis has been fixed in the latest Mesh release. We just need to bump the versions here.

**Comment by ardatan** [comment] 2022-10-05 03:47
Closing the issue due to the missing reproduction. Feel free to create a new issue with a reproduction on CodeSandbox or StackBlitz. Thanks.

**Closed by ardatan** 2022-10-05 03:47 UTC
