### ISSUE TITLE
Usage with NextJs and Apollo fails build

### ISSUE THREAD

**Issue by cmwhited** [graphprotocol/graph-client#242] opened 2022-09-12 22:41 UTC
# Description

Tried to utilize the graph-client with a nextjs app using apollo with the `@graphprotocol/client-apollo` lib.
The build fails with error:

```txt
yarn run v1.22.17
$ yarn build:types && next build
$ graphclient build
💡 GraphClient Cleaning existing artifacts
💡 GraphClient Reading the configuration
💡 GraphClient Generating the unified schema
💡 GraphClient Generating artifacts
💡 GraphClient Generating index file in TypeScript
💡 GraphClient Writing index.ts for ESM to the disk.
💡 GraphClient Cleanup
💡 GraphClient Done! => /Users/chris.whited/dev/edgeandnode/test-graph-client-apollo/.graphclient
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
warn  - Compiled with warnings

./node_modules/@graphql-mesh/utils/index.mjs
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./.graphclient/index.ts
./graphql/sdk.ts
./graphql/index.ts
./pages/_app.tsx

./node_modules/@graphql-tools/url-loader/esm/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@graphql-mesh/graphql/index.mjs
./.graphclient/index.ts
./graphql/sdk.ts
./graphql/index.ts
./pages/_app.tsx

info  - Collecting page data ...Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/chris.whited/dev/edgeandnode/test-graph-client-apollo/node_modules/@apollo/client/core' is not supported resolving ES modules imported from /Users/chris.whited/dev/edgeandnode/test-graph-client-apollo/node_modules/@graphql-mesh/apollo-link/index.mjs
Did you mean to import @apollo/client/core/core.cjs?
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:433:17)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/chris.whited/dev/edgeandnode/test-graph-client-apollo/node_modules/@apollo/client/core'
}

> Build error occurred
Error: Failed to collect page data for /
    at /Users/chris.whited/dev/edgeandnode/test-graph-client-apollo/node_modules/next/dist/build/utils.js:771:15 {
  type: 'Error'
}
error Command failed with exit code 1.
```

[example repo](https://github.com/cmwhited/test-graph-client-apollo)

**Comment by ardatan** [comment] 2022-09-13 00:18
Please share a reproduction on CodeSandbox or StackBlitz. So we can use the same environment.

**Comment by cmwhited** [comment] 2022-09-13 00:39
[Here you go](https://stackblitz.com/edit/nextjs-e2z2w6?file=.graphclientrc.yml)

**Comment by ardatan** [comment] 2022-09-13 02:04
@cmwhited Could you update the sandbox because I only see a template for Next.js?

**Comment by cmwhited** [comment] 2022-09-13 02:43
> @cmwhited Could you update the sandbox because I only see a template for Next.js?

Try this link: https://stackblitz.com/edit/test-graph-client-apollo?file=package.json

**Comment by cmwhited** [comment] 2022-09-13 03:02
If that doesn't work, try https://stackblitz.com/edit/nextjs-v4fvep?file=package.json

**Comment by bxav** [comment] 2022-09-29 14:48
Hi @cmwhited I have the same issue. Did you find a solution?

**Comment by cmwhited** [comment] 2022-09-29 17:17
> Hi @cmwhited I have the same issue. Did you find a solution?

No solution yet

**Comment by bxav** [comment] 2022-09-30 07:05
I directly use the underlying package. Works for me now. I don't really have time to go deeper but it looks like there are some import fixes in the next release of '@graphql-mesh/apollo-link'

```js
import * as GraphClient from './.graphclient';
const { MeshApolloLink } = require('@graphql-mesh/apollo-link');

const client = new ApolloClient({
  link: new MeshApolloLink(GraphClient),
```

**Comment by ardatan** [comment] 2022-10-10 13:08
Fixed in the latest release!

**Closed by ardatan** 2022-10-10 13:08 UTC
Labels: bug
